spring.application.name=chathub-backend
server.port=8000

# MongoDB
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017}
spring.data.mongodb.database=${DB_NAME:chathub}

# JWT
jwt.secret=${JWT_SECRET_KEY:CgUu5hMWeF/LUpup1SIwFd1TBt8FRP6ScUcSeO9b/z3RmmkI7b2DBjWyocdpd9nE2tOTeKh2JYPq+1lHusZUVg==}
jwt.expiration-minutes=1440

# File Upload
app.upload-dir=./uploads
server.address=0.0.0.0
app.base-url=

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.chathub=INFO
logging.level.org.springframework.web.socket=INFO

# Support & Email
resend.api.key=${RESEND_API_KEY:re_4Xb4vEiW_BAffiREnhDBLF8cPz1MZXVBm}
support.email=${SUPPORT_EMAIL:rezimtit001@gmail.com}
